111

diff --git a/target/bin/workerBot b/target/bin/workerBot
--- a/target/bin/workerBot
+++ b/target/bin/workerBot
@@ -14,13 +14,29 @@
 #  See the License for the specific language governing permissions and
 #  limitations under the License.
 # ----------------------------------------------------------------------------
-
-#   Copyright (c) 2001-2002 The Apache Software Foundation.  All rights
+#
+#   Copyright (c) 2001-2006 The Apache Software Foundation.  All rights
 #   reserved.
 
-BASEDIR=`dirname $0`/..
-BASEDIR=`(cd "$BASEDIR"; pwd)`
 
+# resolve links - $0 may be a softlink
+PRG="$0"
+
+while [ -h "$PRG" ]; do
+  ls=`ls -ld "$PRG"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    PRG="$link"
+  else
+    PRG=`dirname "$PRG"`/"$link"
+  fi
+done
+
+PRGDIR=`dirname "$PRG"`
+BASEDIR=`cd "$PRGDIR/.." >/dev/null; pwd`
+
+# Reset the REPO variable. If you need to influence this use the environment setup file.
+REPO=
 
 
 # OS specific support.  $var _must_ be set to either true or false.
@@ -34,9 +50,13 @@ case "`uname`" in
            else
              echo "Using Java version: $JAVA_VERSION"
            fi
-           if [ -z "$JAVA_HOME" ] ; then
-             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
-           fi
+		   if [ -z "$JAVA_HOME" ]; then
+		      if [ -x "/usr/libexec/java_home" ]; then
+			      JAVA_HOME=`/usr/libexec/java_home`
+			  else
+			      JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
+			  fi
+           fi       
            ;;
 esac
 
@@ -67,8 +87,8 @@ if [ -z "$JAVACMD" ] ; then
 fi
 
 if [ ! -x "$JAVACMD" ] ; then
-  echo "Error: JAVA_HOME is not defined correctly."
-  echo "  We cannot execute $JAVACMD"
+  echo "Error: JAVA_HOME is not defined correctly." 1>&2
+  echo "  We cannot execute $JAVACMD" 1>&2
   exit 1
 fi
 
@@ -77,8 +97,16 @@ then
   REPO="$BASEDIR"/repo
 fi
 
-CLASSPATH=$CLASSPATH_PREFIX:"$BASEDIR"/etc:"$REPO"/org/telegram/telegrambots/3.5/telegrambots-3.5.jar:"$REPO"/org/telegram/telegrambots-meta/3.5/telegrambots-meta-3.5.jar:"$REPO"/com/google/inject/guice/4.1.0/guice-4.1.0.jar:"$REPO"/javax/inject/javax.inject/1/javax.inject-1.jar:"$REPO"/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:"$REPO"/com/google/guava/guava/19.0/guava-19.0.jar:"$REPO"/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:"$REPO"/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.8.7/jackson-jaxrs-json-provider-2.8.7.jar:"$REPO"/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.8.7/jackson-jaxrs-base-2.8.7.jar:"$REPO"/com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7.jar:"$REPO"/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.7/jackson-module-jaxb-annotations-2.8.7.jar:"$REPO"/com/fasterxml/jackson/core/jackson-databind/2.8.7/jackson-databind-2.8.7.jar:"$REPO"/org/glassfish/jersey/media/jersey-media-json-jackson/2.25.1/jersey-media-json-jackson-2.25.1.jar:"$REPO"/org/glassfish/jersey/core/jersey-common/2.25.1/jersey-common-2.25.1.jar:"$REPO"/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.25.1/jersey-guava-2.25.1.jar:"$REPO"/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar:"$REPO"/org/glassfish/jersey/ext/jersey-entity-filtering/2.25.1/jersey-entity-filtering-2.25.1.jar:"$REPO"/org/glassfish/jersey/containers/jersey-container-grizzly2-http/2.25.1/jersey-container-grizzly2-http-2.25.1.jar:"$REPO"/org/glassfish/hk2/external/javax.inject/2.5.0-b32/javax.inject-2.5.0-b32.jar:"$REPO"/org/glassfish/grizzly/grizzly-http-server/2.3.28/grizzly-http-server-2.3.28.jar:"$REPO"/org/glassfish/grizzly/grizzly-http/2.3.28/grizzly-http-2.3.28.jar:"$REPO"/org/glassfish/grizzly/grizzly-framework/2.3.28/grizzly-framework-2.3.28.jar:"$REPO"/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar:"$REPO"/org/glassfish/jersey/core/jersey-server/2.25.1/jersey-server-2.25.1.jar:"$REPO"/org/glassfish/jersey/core/jersey-client/2.25.1/jersey-client-2.25.1.jar:"$REPO"/org/glassfish/jersey/media/jersey-media-jaxb/2.25.1/jersey-media-jaxb-2.25.1.jar:"$REPO"/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar:"$REPO"/org/glassfish/hk2/hk2-api/2.5.0-b32/hk2-api-2.5.0-b32.jar:"$REPO"/org/glassfish/hk2/hk2-utils/2.5.0-b32/hk2-utils-2.5.0-b32.jar:"$REPO"/org/glassfish/hk2/external/aopalliance-repackaged/2.5.0-b32/aopalliance-repackaged-2.5.0-b32.jar:"$REPO"/org/glassfish/hk2/hk2-locator/2.5.0-b32/hk2-locator-2.5.0-b32.jar:"$REPO"/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:"$REPO"/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:"$REPO"/org/json/json/20160810/json-20160810.jar:"$REPO"/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar:"$REPO"/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:"$REPO"/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:"$REPO"/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:"$REPO"/org/apache/httpcomponents/httpmime/4.5.3/httpmime-4.5.3.jar:"$REPO"/commons-io/commons-io/2.5/commons-io-2.5.jar:"$REPO"/ru/cteam/cteambot/1.0-SNAPSHOT/cteambot-1.0-SNAPSHOT.jar
-EXTRA_JVM_ARGUMENTS=""
+CLASSPATH="$BASEDIR"/etc:"$REPO"/org/telegram/telegrambots/3.5/telegrambots-3.5.jar:"$REPO"/org/telegram/telegrambots-meta/3.5/telegrambots-meta-3.5.jar:"$REPO"/com/google/inject/guice/4.1.0/guice-4.1.0.jar:"$REPO"/javax/inject/javax.inject/1/javax.inject-1.jar:"$REPO"/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:"$REPO"/com/google/guava/guava/19.0/guava-19.0.jar:"$REPO"/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:"$REPO"/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.8.7/jackson-jaxrs-json-provider-2.8.7.jar:"$REPO"/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.8.7/jackson-jaxrs-base-2.8.7.jar:"$REPO"/com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7.jar:"$REPO"/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.7/jackson-module-jaxb-annotations-2.8.7.jar:"$REPO"/com/fasterxml/jackson/core/jackson-databind/2.8.7/jackson-databind-2.8.7.jar:"$REPO"/org/glassfish/jersey/media/jersey-media-json-jackson/2.25.1/jersey-media-json-jackson-2.25.1.jar:"$REPO"/org/glassfish/jersey/core/jersey-common/2.25.1/jersey-common-2.25.1.jar:"$REPO"/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.25.1/jersey-guava-2.25.1.jar:"$REPO"/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar:"$REPO"/org/glassfish/jersey/ext/jersey-entity-filtering/2.25.1/jersey-entity-filtering-2.25.1.jar:"$REPO"/org/glassfish/jersey/containers/jersey-container-grizzly2-http/2.25.1/jersey-container-grizzly2-http-2.25.1.jar:"$REPO"/org/glassfish/hk2/external/javax.inject/2.5.0-b32/javax.inject-2.5.0-b32.jar:"$REPO"/org/glassfish/grizzly/grizzly-http-server/2.3.28/grizzly-http-server-2.3.28.jar:"$REPO"/org/glassfish/grizzly/grizzly-http/2.3.28/grizzly-http-2.3.28.jar:"$REPO"/org/glassfish/grizzly/grizzly-framework/2.3.28/grizzly-framework-2.3.28.jar:"$REPO"/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar:"$REPO"/org/glassfish/jersey/core/jersey-server/2.25.1/jersey-server-2.25.1.jar:"$REPO"/org/glassfish/jersey/core/jersey-client/2.25.1/jersey-client-2.25.1.jar:"$REPO"/org/glassfish/jersey/media/jersey-media-jaxb/2.25.1/jersey-media-jaxb-2.25.1.jar:"$REPO"/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar:"$REPO"/org/glassfish/hk2/hk2-api/2.5.0-b32/hk2-api-2.5.0-b32.jar:"$REPO"/org/glassfish/hk2/hk2-utils/2.5.0-b32/hk2-utils-2.5.0-b32.jar:"$REPO"/org/glassfish/hk2/external/aopalliance-repackaged/2.5.0-b32/aopalliance-repackaged-2.5.0-b32.jar:"$REPO"/org/glassfish/hk2/hk2-locator/2.5.0-b32/hk2-locator-2.5.0-b32.jar:"$REPO"/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:"$REPO"/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:"$REPO"/org/json/json/20160810/json-20160810.jar:"$REPO"/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar:"$REPO"/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:"$REPO"/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:"$REPO"/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:"$REPO"/org/apache/httpcomponents/httpmime/4.5.3/httpmime-4.5.3.jar:"$REPO"/commons-io/commons-io/2.5/commons-io-2.5.jar:"$REPO"/ru/cteam/cteambot/1.0-SNAPSHOT/cteambot-1.0-SNAPSHOT.jar
+
+ENDORSED_DIR=
+if [ -n "$ENDORSED_DIR" ] ; then
+  CLASSPATH=$BASEDIR/$ENDORSED_DIR/*:$CLASSPATH
+fi
+
+if [ -n "$CLASSPATH_PREFIX" ] ; then
+  CLASSPATH=$CLASSPATH_PREFIX:$CLASSPATH
+fi
 
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin; then
@@ -89,12 +117,12 @@ if $cygwin; then
   [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
 fi
 
-exec "$JAVACMD" $JAVA_OPTS \
-  $EXTRA_JVM_ARGUMENTS \
+exec "$JAVACMD" $JAVA_OPTS  \
   -classpath "$CLASSPATH" \
   -Dapp.name="workerBot" \
   -Dapp.pid="$$" \
   -Dapp.repo="$REPO" \
+  -Dapp.home="$BASEDIR" \
   -Dbasedir="$BASEDIR" \
   Bot \
   "$@"
